# Generated by Django 4.2.1 on 2023-05-15 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='House')),
                ('house_rent', models.IntegerField()),
                ('house_description', models.TextField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('amenities', models.ManyToManyField(to='HRSApp.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('square_feet', models.IntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('FatherName', models.CharField(max_length=100)),
                ('ContactNumber', models.CharField(max_length=20)),
                ('NidNumber', models.CharField(max_length=20)),
                ('NID', models.ImageField(upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='House')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRSApp.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Updated_at', models.DateField(auto_now=True)),
                ('AreaName', models.ManyToManyField(to='HRSApp.areaname')),
                ('Block', models.ManyToManyField(to='HRSApp.block')),
                ('City', models.ManyToManyField(to='HRSApp.city')),
                ('Division', models.ManyToManyField(to='HRSApp.division')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_images')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HRSApp.rentaladvertisement')),
            ],
        ),
    ]
