# Generated by Django 4.2.1 on 2023-05-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRSApp', '0002_remove_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='User_info',
        ),
    ]
