# Generated by Django 4.2.1 on 2023-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRSApp', '0003_rename_profile_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=100)),
                ('Rent', models.CharField(max_length=6)),
                ('HouseDetails', models.CharField(max_length=200)),
                ('SquareFeet', models.CharField(max_length=50)),
                ('PhoneNo', models.IntegerField()),
                ('HouseImage', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
