# Generated by Django 4.2.1 on 2023-05-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRSApp', '0004_housepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='houseaddress',
            name='AreaName',
        ),
        migrations.RemoveField(
            model_name='houseaddress',
            name='Block',
        ),
        migrations.RemoveField(
            model_name='houseaddress',
            name='City',
        ),
        migrations.RemoveField(
            model_name='houseaddress',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='house',
        ),
        migrations.DeleteModel(
            name='AdvertisementImage',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='AreaName',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='HouseAddress',
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
        migrations.DeleteModel(
            name='RentalAdvertisement',
        ),
    ]
