# Generated by Django 4.2.1 on 2023-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRSApp', '0005_remove_house_amenities_remove_houseaddress_areaname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='HouseImage',
            field=models.ImageField(upload_to='media/Post/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='NID',
            field=models.ImageField(upload_to='media/User/'),
        ),
    ]
