# Generated by Django 4.2.1 on 2023-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRSApp', '0006_alter_housepost_houseimage_alter_user_info_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepost',
            name='HouseImage',
            field=models.ImageField(upload_to='Post/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='NID',
            field=models.ImageField(upload_to='User/'),
        ),
    ]
